// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";

var el = document.querySelector("#root");

if (!(el == null)) {
  ReactDom.render(React.createElement("div", undefined, "test"), el);
}

export {
  
}
/* el Not a pure module */
